import type { ChromeDict, ContentDict } from '../i18n';
import { useTranslator } from '../i18n';

export const ERP_CHROME: ChromeDict = {
  'window.title': { ru: 'Утолить Желания', en: 'Sate Desires' },

  'control.arouse': { ru: 'ВОЗБУЖДАТЬСЯ', en: 'AROUSE' },
  'control.yield': { ru: 'ПОДДАВАТЬСЯ', en: 'YIELD' },
  'control.moan': { ru: 'СТОНАТЬ', en: 'MOAN' },
  'control.hidden': { ru: 'СКРЫТНО', en: 'DISCREET' },
  'control.flip': { ru: 'ПЕРЕВЕРНУТЬСЯ', en: 'FLIP OVER' },
  'control.stop': { ru: 'ОСТАНОВИТЬСЯ', en: 'STOP' },

  'bar.me': { ru: 'Я', en: 'Me' },
  'bar.partner': { ru: 'Партнёр', en: 'Partner' },

  'tab.actions': { ru: 'ДЕЙСТВИЯ', en: 'ACTIONS' },
  'tab.status': { ru: 'СТАТУС', en: 'STATUS' },
  'tab.erp': { ru: 'ЭРП', en: 'ERP' },
  'tab.editor': { ru: 'РЕДАКТОР', en: 'EDITOR' },

  'base_tuning.title': {
    ru: 'Базовые настройки новых действий',
    en: 'Defaults for new actions',
  },
  'label.speed': { ru: 'Скорость', en: 'Speed' },
  'label.force': { ru: 'Сила', en: 'Force' },

  'speed.0': { ru: 'Медленно', en: 'Slow' },
  'speed.1': { ru: 'Средне', en: 'Medium' },
  'speed.2': { ru: 'Быстро', en: 'Fast' },
  'speed.3': { ru: 'Неистово', en: 'Frantic' },
  'force.0': { ru: 'Нежно', en: 'Gentle' },
  'force.1': { ru: 'Уверенно', en: 'Firm' },
  'force.2': { ru: 'Сильно', en: 'Hard' },
  'force.3': { ru: 'Жестко', en: 'Rough' },

  'actions.title': { ru: 'Действия', en: 'Actions' },
  'actions.empty': { ru: 'Нет доступных действий.', en: 'No available actions.' },
  'nodes.me': { ru: 'Я', en: 'Me' },
  'nodes.partner': { ru: 'Партнёр', en: 'Partner' },

  'links.title': { ru: 'Активные связки', en: 'Active links' },
  'links.stop_tooltip': { ru: 'Остановить связку', en: 'Stop link' },
  'links.default_action': { ru: 'ДЕЙСТВИЕ', en: 'ACTION' },
  'links.toggle_finish_tooltip': {
    ru: 'Переключить режим завершения',
    en: 'Toggle finish mode',
  },
  'links.until_climax': { ru: 'ДО КЛИМАКСА', en: 'UNTIL CLIMAX' },
  'links.until_stop': { ru: 'ПОКА НЕ ОСТАНОВЛЮСЬ', en: 'UNTIL I STOP' },

  'penis.title': { ru: 'Настройки члена', en: 'Penis settings' },
  'penis.knot': { ru: 'Узел', en: 'Knot' },
  'penis.knot_on': { ru: 'ДО УЗЛА', en: 'WITH KNOT' },
  'penis.knot_off': { ru: 'БЕЗ УЗЛА', en: 'NO KNOT' },
  'penis.where_climax': { ru: 'Куда кончить', en: 'Where to finish' },

  'filter.title': { ru: 'Фильтр', en: 'Filter' },
  'filter.placeholder': {
    ru: 'Поиск взаимодействия...',
    en: 'Search interaction...',
  },

  'pref.dislike': { ru: 'Не нравится', en: 'Dislike' },
  'pref.like': { ru: 'Нравится', en: 'Like' },
  'pref.neutral': { ru: 'Нейтрально', en: 'Neutral' },

  'organ.fallback_name': { ru: 'Орган', en: 'Organ' },
  'organ.active': { ru: 'активен', en: 'active' },
  'organ.sensitivity': { ru: 'Чувств.:', en: 'Sens.:' },
  'organ.pain': { ru: 'Боль:', en: 'Pain:' },
  'organ.overflow': { ru: 'ПЕРЕПОЛН.', en: 'OVERFLOW' },
  'organ.arousal': { ru: 'Возбуждение', en: 'Arousal' },
  'erect.auto': { ru: 'АВТО', en: 'AUTO' },
  'erect.none': { ru: 'МЯГКИЙ', en: 'SOFT' },
  'erect.partial': { ru: 'ВОЗБУЖДЕН', en: 'AROUSED' },
  'erect.hard': { ru: 'КРЕПКИЙ', en: 'HARD' },
  'organ.fill': { ru: 'Наполненность:', en: 'Fullness:' },
  'organ.passive_links': { ru: 'Воздействия на орган', en: 'Acting on organ' },
  'organ.active_links': { ru: 'Орган воздействует', en: 'Organ acts' },

  'arousal.charge': { ru: 'Заряд:', en: 'Charge:' },
  'arousal.for_orgasm': { ru: 'для оргазма', en: 'for orgasm' },
  'arousal.wellbeing': { ru: 'Самочувствие:', en: 'Wellbeing:' },
  'arousal.normal': { ru: 'нормально', en: 'normal' },
  'arousal.overstim': { ru: 'СВЕРХ-СТИМУЛЯЦИЯ', en: 'OVERSTIMULATION' },

  'status.title': { ru: 'Статус', en: 'Status' },
  'status.empty': { ru: 'Пусто (entries не пришли)', en: 'Empty (no entries)' },

  'bool.on': { ru: 'ВКЛ', en: 'ON' },
  'bool.off': { ru: 'ВЫКЛ', en: 'OFF' },

  'list.add_placeholder': { ru: 'добавить...', en: 'add...' },
  'section.params': { ru: 'Параметры', en: 'Parameters' },

  'editor.title': { ru: 'Редактор действий', en: 'Action editor' },
  'editor.templates': { ru: 'Шаблоны', en: 'Templates' },
  'editor.no_templates': {
    ru: 'Нет доступных шаблонов.',
    en: 'No available templates.',
  },
  'editor.my_custom': { ru: 'Мои кастомные', en: 'My custom' },
  'editor.empty_custom': { ru: 'Пока пусто.', en: 'Empty for now.' },
  'editor.pick_hint': {
    ru: 'Выбери слева шаблон или своё действие.',
    en: 'Pick a template or your action on the left.',
  },
  'editor.basic': { ru: 'Основное', en: 'Basic' },
  'editor.name': { ru: 'Название', en: 'Name' },
  'editor.fields': { ru: 'Поля', en: 'Fields' },
  'editor.no_fields': {
    ru: 'Поля не пришли (или backend ещё не отдал выбранное действие полностью).',
    en: "Fields not received (backend hasn't fully sent the selected action).",
  },
  'editor.raw_hint': {
    ru: 'В RAW можно править payload полей. Если JSON сломан — уйдёт обычный вариант.',
    en: 'In RAW you can edit the fields payload. If the JSON is broken, the normal variant is sent.',
  },
  'editor.create': { ru: 'СОЗДАТЬ КАСТОМ', en: 'CREATE CUSTOM' },
  'editor.save': { ru: 'СОХРАНИТЬ', en: 'SAVE' },
  'editor.delete': { ru: 'УДАЛИТЬ', en: 'DELETE' },
  'editor.dirty_hint': {
    ru: 'Локальные правки не будут перезатираться обновлениями UI до сохранения или смены выбора.',
    en: "Local edits won't be overwritten by UI updates until you save or change the selection.",
  },

  'kinks.title': { ru: 'Фетиши', en: 'Fetishes' },
  'kinks.search_placeholder': { ru: 'Поиск по кинкам...', en: 'Search kinks...' },
  'kinks.settings': { ru: 'Настройки', en: 'Settings' },
  'kinks.no_results': {
    ru: 'Ничего не найдено по фильтрам.',
    en: 'Nothing found for the filters.',
  },
  'kinks.cat_all': { ru: 'ВСЕ', en: 'ALL' },

  'tab.placeholder': { ru: 'Контент вкладки позже.', en: 'Tab content later.' },
  'modal.set_arousal': {
    ru: 'Установить возбуждение (0–100)',
    en: 'Set arousal (0–100)',
  },
  'modal.set_sensitivity': {
    ru: 'Чувствительность (например 0–2)',
    en: 'Sensitivity (e.g. 0–2)',
  },
  'btn.cancel': { ru: 'Отмена', en: 'Cancel' },
};

export const ERP_CONTENT: ContentDict = {
  hands: 'Hands',
  legs: 'Legs',
  tail: 'Tail',
  mouth: 'Mouth',
  anus: 'Anus',
  breasts: 'Breasts',
  vagina: 'Vagina',
  penis: 'Penis',
  body: 'Body',

  outside: 'Outside',
  inside: 'Inside',

  '/datum/erp_action/other/anus/butt': 'Work with butt',
  '/datum/erp_action/other/anus/face': 'Sit on face',
  '/datum/erp_action/other/anus/force_face': 'Force sit on face',
  '/datum/erp_action/other/anus/rubbing': 'Rub with butt',
  '/datum/erp_action/other/anus/sex': 'Ride with anus',
  '/datum/erp_action/other/anus/tail': 'Use tail with butt',
  '/datum/erp_action/other/body/grinding': 'Nuzzle with face',
  '/datum/erp_action/other/body/rubbing': 'Rub body',
  '/datum/erp_action/other/breasts/breast_feed': 'Force breastfeed',
  '/datum/erp_action/other/breasts/teasing': 'Rub with breasts',
  '/datum/erp_action/other/breasts/titjob': 'Titjob',
  '/datum/erp_action/other/hands/breasts_play': 'Grope breasts',
  '/datum/erp_action/other/hands/finger_anal': 'Finger anus',
  '/datum/erp_action/other/hands/finger_oral': 'Fingers in mouth',
  '/datum/erp_action/other/hands/finger_vaginal': 'Finger vagina',
  '/datum/erp_action/other/hands/force_armpits': 'Press to armpits',
  '/datum/erp_action/other/hands/force_crotch': 'Press to crotch',
  '/datum/erp_action/other/hands/masturbation': 'Stroke penis by hand',
  '/datum/erp_action/other/hands/milking_breasts': 'Milk breasts',
  '/datum/erp_action/other/hands/milking_penis': 'Milk penis',
  '/datum/erp_action/other/hands/rubbing': 'Grope body',
  '/datum/erp_action/other/hands/toy_anal': 'Sex toy (anal)',
  '/datum/erp_action/other/hands/toy_oral': 'Sex toy (oral)',
  '/datum/erp_action/other/hands/toy_vaginal': 'Sex toy (vaginal)',
  '/datum/erp_action/other/hands/spanking': 'Spank buttocks',
  '/datum/erp_action/other/hands/tease_tail': 'Stroke tail',
  '/datum/erp_action/other/hands/tease_testicles': 'Stroke testicles by hand',
  '/datum/erp_action/other/hands/tease_vagina': 'Stroke clit by hand',
  '/datum/erp_action/other/hands/touching': 'Caress',
  '/datum/erp_action/other/legs/footfetish': 'Force to lick feet',
  '/datum/erp_action/other/legs/footjob': 'Footjob',
  '/datum/erp_action/other/legs/legsjob': 'Thighjob',
  '/datum/erp_action/other/legs/teasing': 'Rub with leg',
  '/datum/erp_action/other/mouth/blowjob': 'Blowjob',
  '/datum/erp_action/other/mouth/breast_feed': 'Lick breasts',
  '/datum/erp_action/other/mouth/cunnilingus': 'Cunnilingus',
  '/datum/erp_action/other/mouth/finger_lick': 'Lick fingers',
  '/datum/erp_action/other/mouth/foot_lick': 'Lick feet',
  '/datum/erp_action/other/mouth/kiss': 'Kiss',
  '/datum/erp_action/other/mouth/rimming': 'Rimming',
  '/datum/erp_action/other/penis/anal_sex': 'Anal sex',
  '/datum/erp_action/other/penis/butt_job': 'Buttjob',
  '/datum/erp_action/other/penis/force_blowjob': 'Force blowjob',
  '/datum/erp_action/other/penis/masturbation': 'Masturbate at partner',
  '/datum/erp_action/other/penis/oral_sex': 'Oral sex',
  '/datum/erp_action/other/penis/rubbing': 'Rub with penis',
  '/datum/erp_action/other/penis/sword_fight': 'Sword fight',
  '/datum/erp_action/other/penis/tea_bag': 'Tea bag',
  '/datum/erp_action/other/penis/tit_job': 'Titjob',
  '/datum/erp_action/other/penis/vaginal_sex': 'Vaginal sex',
  '/datum/erp_action/other/tail/anal': 'Fuck ass with tail',
  '/datum/erp_action/other/tail/oral': 'Fuck mouth with tail',
  '/datum/erp_action/other/tail/penis': 'Masturbate with tail',
  '/datum/erp_action/other/tail/rubbing': 'Rub with tail',
  '/datum/erp_action/other/tail/spanking': 'Spank with tail',
  '/datum/erp_action/other/tail/squeeze_breasts': 'Squeeze breasts with tail',
  '/datum/erp_action/other/tail/vaginal': 'Fuck vagina with tail',
  '/datum/erp_action/other/vagina/face': 'Sit with vagina',
  '/datum/erp_action/other/vagina/force_face': 'Force to lick',
  '/datum/erp_action/other/vagina/masturbation': 'Masturbate at partner',
  '/datum/erp_action/other/vagina/rubbing': 'Rub with vagina',
  '/datum/erp_action/other/vagina/scissors': 'Scissoring',
  '/datum/erp_action/other/vagina/sex': 'Ride with vagina',
  '/datum/erp_action/other/vagina/tail': 'Use tail',
  '/datum/erp_action/self/hands/milking_breasts': 'Milk own breasts',
  '/datum/erp_action/self/hands/breasts_play': 'Grope own breasts',
  '/datum/erp_action/self/hands/fingering_anal': 'Fingering (anal)',
  '/datum/erp_action/self/hands/fingering_oral': 'Fingering (oral)',
  '/datum/erp_action/self/hands/fingering_vaginal': 'Fingering (vaginal)',
  '/datum/erp_action/self/hands/masturbate_penis': 'Masturbate penis',
  '/datum/erp_action/self/hands/penis_milking': 'Milk own penis',
  '/datum/erp_action/self/hands/toy_anal': 'Sex toy (anal)',
  '/datum/erp_action/self/hands/toy_oral': 'Sex toy (oral)',
  '/datum/erp_action/self/hands/toy_vaginal': 'Sex toy (vaginal)',
  '/datum/erp_action/self/hands/tail_pet': 'Pet own tail',
  '/datum/erp_action/self/hands/teasing_clitoris': 'Tease clit',
  '/datum/erp_action/self/tail/anal_tail': 'Anal play with tail',
  '/datum/erp_action/self/tail/squeeze_breasts': 'Squeeze own breasts with tail',
  '/datum/erp_action/self/tail/suck_tail': 'Suck own tail',
  '/datum/erp_action/self/tail/penis_tail': 'Masturbate penis with tail',
  '/datum/erp_action/self/tail/vag_tail': 'Vaginal play with tail',

  '/datum/kink/bondage': 'Bondage',
  '/datum/kink/domination': 'Domination',
  '/datum/kink/submissive': 'Submission',
  '/datum/kink/gentle': 'Gentleness',
  '/datum/kink/rough': 'Roughness',
  '/datum/kink/public': 'Public',

  '/datum/kink/bondage:desc':
    "Aroused by restricting a partner's or your own freedom.",
  '/datum/kink/domination:desc': 'Aroused by control and the leading role.',
  '/datum/kink/submissive:desc': 'Aroused by the submissive role.',
  '/datum/kink/gentle:desc': 'Aroused by gentle sex.',
  '/datum/kink/rough:desc': 'Aroused by rough and hard sex.',
  '/datum/kink/public:desc':
    'Aroused by sex while seen by those not in the current session.',

  Доминирование: 'Domination',
  Общее: 'General',
  Подчинение: 'Submission',
  Фетиши: 'Fetishes',
};

export function useErpTranslator() {
  return useTranslator(ERP_CHROME, ERP_CONTENT);
}
