import { useLang } from '../i18n';

const RU: Record<string, string> = {
  'Round Start': 'Начало раунда',
  'Round Started': 'Раунд начался',
  'Setting Up': 'Подготовка',
  'Starts In': 'Начнётся через',
  'Delayed': 'Отложено',
  'DELAYED': 'ОТЛОЖЕНО',
  'Join Now': 'Войти сейчас',
  'Ready': 'Готов',
  'Ready Order': 'Порядок готовности',
  'Change Character': 'Сменить персонажа',
  'Looking Glass': 'Зеркало',

  'Identity': 'Личность',
  'Appearance': 'Внешность',
  'Gameplay': 'Геймплей',
  'Character Profile': 'Профиль персонажа',
  'Intimacy': 'Близость',
  'Settings': 'Настройки',

  'Interface': 'Интерфейс',
  'Interface Theme': 'Тема интерфейса',
  'Display': 'Дисплей',
  'Audio & Round': 'Звук и раунд',
  'Intimacy & Tools': 'Близость и инструменты',
  'Character Setup': 'Настройка персонажа',

  'Hotkeys': 'Горячие клавиши',
  'Action Buttons': 'Кнопки действий',
  'Fancy tgui': 'Модный tgui',
  'Lock tgui Layout': 'Зафиксировать tgui',
  'Window Flashing': 'Мигание окна',
  'See Non-mob Chat': 'Видеть чат не-мобов',
  'Ambient Occlusion': 'Затенение (AO)',
  'Auto-fit Viewport': 'Авто-подгон вьюпорта',
  'Widescreen': 'Широкий экран',
  'Pixel Size': 'Размер пикселя',
  'Scaling Method': 'Метод масштабирования',
  'Lobby Music': 'Музыка лобби',
  'Admin MIDIs': 'Админ-MIDI',
  'Midround Antag': 'Мидраунд-антаг',
  'Intimacy Opt-in (ERP)': 'Согласие на близость (ERP)',
  'Toggle Bitfields': 'Переключить битфилды',
  'Keybinds': 'Клавиши',
  'Save Preferences': 'Сохранить настройки',
  'Language': 'Язык',

  'Choose Species': 'Выбор расы',
  'Choose Faith': 'Выбор веры',
  'Class & Roles': 'Класс и роли',
  'Class / Jobs': 'Класс / Работы',
  'Class': 'Класс',
  'Special Role': 'Спец. роль',
  'Special Roles': 'Спец. роли',
  'Triumphs': 'Триумфы',
  'Triumph Shop': 'Магазин триумфов',
  'Balance': 'Баланс',
  'Relations': 'Отношения',
  'Family': 'Семья',
  'Spouse Pref': 'Супруг(а)',
  'Gender Pref': 'Пол',
  'Standing': 'Статус',
  'Voice': 'Голос',
  'Flavour': 'Описание',
  'Flavour Text': 'Описание',
  'Profile Link': 'Ссылка на профиль',

  'Current Species': 'Текущая раса',
  'Current species': 'Текущая раса',
  'Selected species': 'Выбранная раса',
  'Apply Species': 'Применить расу',
  'Apply species': 'Применить расу',
  'Ready to apply': 'Готово к применению',
  'Unavailable': 'Недоступно',

  'Name': 'Имя',
  'Body Type': 'Телосложение',
  'Pronouns': 'Местоимения',
  'Age': 'Возраст',
  'Ages': 'Возраст',
  'Dominant Hand': 'Ведущая рука',
  'Quirks': 'Причуды',
  'Player Quality': 'Качество игрока',
  'Culture': 'Культура',
  'Ancestry': 'Происхождение',
  'Descriptors': 'Дескрипторы',
  'Food Preferences': 'Пищевые предпочтения',
  'Stat modifiers': 'Модификаторы характеристик',
  'Tags': 'Теги',

  'Patron': 'Патрон',
  'Patrons': 'Патроны',
  'Domain': 'Домен',
  'About': 'Описание',
  'Boons': 'Дары',
  'Sins': 'Грехи',

  'Body': 'Тело',
  'Taur Body': 'Тело тавра',
  'Color': 'Цвет',
  'Colors': 'Цвета',
  'Markings': 'Отметины',
  'Tertiary': 'Третичный',
  'Type': 'Тип',
  'Options': 'Опции',
  'Style': 'Стиль',
  'Backdrop': 'Фон',
  'Backdrop tile': 'Фоновый тайл',
  'Face Details': 'Детали лица',
  'Underwear': 'Бельё',

  'Voice Type': 'Тип голоса',
  'Voice Color': 'Цвет голоса',
  'Accent': 'Акцент',

  'OOC': 'OOC',
  'OOC Chat': 'OOC чат',
  'OOC Notes': 'OOC заметки',
  'OOC Extra': 'OOC доп.',
  'Send OOC': 'Отправить OOC',
  'Compact OOC chat': 'Компактный OOC-чат',
  'Expand OOC chat': 'Развернуть OOC-чат',
  'Set Headshot URL': 'Задать URL портрета',
  'No headshot set': 'Портрет не задан',
  'Current': 'Текущий',

  'All': 'Все',
  'Open': 'Доступно',
  'Locked': 'Заблокировано',
  'Unlocked': 'Разблокировано',
  'Randomise': 'Случайно',
  'Randomise Appearance': 'Случайная внешность',
  'Collapse window': 'Свернуть окно',
  'Expand window': 'Развернуть окно',

  'No description.': 'Нет описания.',
  'None': 'Нет',
  'Unknown': 'Неизвестно',
  'Unnamed': 'Без имени',
  'Select': 'Выбрать',
  'ENABLED': 'ВКЛючено',
  'DISABLED': 'ОТКЛючено',
  'ON': 'ВКЛ',
  'OFF': 'ВЫКЛ',
  'Yes': 'Да',
  'No': 'Нет',

  'Message OOC...': 'Сообщение OOC...',
  'Search species...': 'Поиск расы...',

  'Rotate': 'Поворот',
  'Rotate left': 'Повернуть влево',
  'Rotate right': 'Повернуть вправо',
  'Underwear Layer': 'Слой белья',
  'Work Clothes Layer': 'Слой рабочей одежды',
  'No OOC messages.': 'Нет OOC-сообщений.',
  'Front': 'Спереди',
  'Side': 'Сбоку',

  'Loadout': 'Лодаут',
  'Undo': 'Отменить',
  'Save': 'Сохранить',
  'Done': 'Готово',
  'Undo from save': 'Откатить к сохранению',
  'Reset colors': 'Сбросить цвета',
  'Smaller elements': 'Мельче элементы',
  'Larger elements': 'Крупнее элементы',
  'Reset element scale': 'Сбросить масштаб',
  "Choose this faith's godhead": 'Выбрать божество этой веры',
};

export function usePrefsTp() {
  const lang = useLang();
  return <T,>(value: T): T => {
    if (typeof value !== 'string' || lang !== 'ru') {
      return value;
    }
    return (RU[value] ?? value) as T;
  };
}
