/datum/preferences/proc/send_character_ui_resources(mob/user)
	switch(read_preference(/datum/preference/choiced/char_theme))
		if("dusty")
			send_dusty_theme(user)
		if("grimshart")
			send_grimshart_theme(user)
		if("paper")
			send_paper_theme(user)
		if("parchment")
			send_parchment_theme(user)

/datum/preferences/proc/send_dusty_theme(mob/user)
	// Background
	user << browse_rsc('html/character_ui/dusty/background&reference/Charsheet_BG.1.png', "Charsheet_BG.1.png")
	// Header
	user << browse_rsc('html/character_ui/dusty/header/0_header_bg.png', "0_header_bg.png")
	user << browse_rsc('html/character_ui/dusty/header/header_charname.png', "header_charname.png")
	user << browse_rsc('html/character_ui/dusty/header/header_class.png', "header_class.png")
	user << browse_rsc('html/character_ui/dusty/header/header_faith.png', "header_faith.png")
	user << browse_rsc('html/character_ui/dusty/header/header_playerckey.png', "header_playerckey.png")
	user << browse_rsc('html/character_ui/dusty/header/header_species.png', "header_species.png")
	user << browse_rsc('html/character_ui/dusty/header/header_patron.png', "header_patron.png")
	user << browse_rsc('html/character_ui/dusty/header/header_pq.png', "header_pq.png")
	// Character Preview
	user << browse_rsc('html/character_ui/dusty/character_preview/charpreview_bg.png', "charpreview_bg.png")
	// Body
	user << browse_rsc('html/character_ui/dusty/body/0_body_bg.png', "0_body_bg.png")
	user << browse_rsc('html/character_ui/dusty/body/body_age.png', "body_age.png")
	user << browse_rsc('html/character_ui/dusty/body/body_flaw.png', "body_flaw.png")
	user << browse_rsc('html/character_ui/dusty/body/body_dominanthand.png', "body_dominanthand.png")
	user << browse_rsc('html/character_ui/dusty/body/body_ancestry.png', "body_ancestry.png")
	user << browse_rsc('html/character_ui/dusty/body/body_pronouns.png', "body_pronouns.png")
	user << browse_rsc('html/character_ui/dusty/body/body_bodytype.png', "body_bodytype.png")
	// Voice
	user << browse_rsc('html/character_ui/dusty/voice/0_voice_bg.png', "0_voice_bg.png")
	user << browse_rsc('html/character_ui/dusty/voice/voice_type.png', "voice_type.png")
	user << browse_rsc('html/character_ui/dusty/voice/voice_accent.png', "voice_accent.png")
	user << browse_rsc('html/character_ui/dusty/voice/voice_colour.png', "voice_colour.png")
	user << browse_rsc('html/character_ui/dusty/voice/voice_colour_blob.png', "voice_colour_blob.png")
	// Family
	user << browse_rsc('html/character_ui/dusty/family/0_family_bg.png', "0_family_bg.png")
	user << browse_rsc('html/character_ui/dusty/family/family_type.png', "family_type.png")
	user << browse_rsc('html/character_ui/dusty/family/gender_pref.png', "gender_pref.png")
	user << browse_rsc('html/character_ui/dusty/family/spouse_pref.png', "spouse_pref.png")
	// Flavour
	user << browse_rsc('html/character_ui/dusty/flavour/0_flavour_bg.png', "0_flavour_bg.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_culture.png', "flavour_culture.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_descriptors.png', "flavour_descriptors.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_descriptors_hover.png', "flavour_descriptors_hover.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_text.png', "flavour_text.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_text_hover.png', "flavour_text_hover.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_foodprefs.png', "flavour_foodprefs.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_foodprefs_hover.png', "flavour_foodprefs_hover.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_preview.png', "flavour_preview.png")
	user << browse_rsc('html/character_ui/dusty/flavour/flavour_preview_hover.png', "flavour_preview_hover.png")
	// Loadout
	user << browse_rsc('html/character_ui/dusty/loadout/0_loadout_bg.png', "0_loadout_bg.png")
	user << browse_rsc('html/character_ui/dusty/loadout/loadout_item1.png', "loadout_item1.png")
	user << browse_rsc('html/character_ui/dusty/loadout/loadout_item2.png', "loadout_item2.png")
	user << browse_rsc('html/character_ui/dusty/loadout/loadout_item3.png', "loadout_item3.png")
	// Triumphs
	user << browse_rsc('html/character_ui/dusty/triumphs/0_triumphs_bg.png', "0_triumphs_bg.png")
	user << browse_rsc('html/character_ui/dusty/triumphs/triumphs_display.png', "triumphs_display.png")
	user << browse_rsc('html/character_ui/dusty/triumphs/triumphs_shop.png', "triumphs_shop.png")
	user << browse_rsc('html/character_ui/dusty/triumphs/triumphs_shop_hover.png', "triumphs_shop_hover.png")
	// Headshot
	user << browse_rsc('html/character_ui/dusty/character_headshot/headshot_bg.png', "headshot_bg.png")
	// OOC
	user << browse_rsc('html/character_ui/dusty/ooc/0_ooc_bg.png', "0_ooc_bg.png")
	user << browse_rsc('html/character_ui/dusty/ooc/ooc_notes.png', "ooc_notes.png")
	user << browse_rsc('html/character_ui/dusty/ooc/ooc_notes_hover.png', "ooc_notes_hover.png")
	user << browse_rsc('html/character_ui/dusty/ooc/ooc_extra.png', "ooc_extra.png")
	user << browse_rsc('html/character_ui/dusty/ooc/ooc_extra_hover.png', "ooc_extra_hover.png")
	user << browse_rsc('html/character_ui/dusty/ooc/ooc_specialroles.png', "ooc_specialroles.png")
	user << browse_rsc('html/character_ui/dusty/ooc/ooc_specialroles_hover.png', "ooc_specialroles_hover.png")
	// Features
	user << browse_rsc('html/character_ui/dusty/features/0_features_bg.png', "0_features_bg.png")
	user << browse_rsc('html/character_ui/dusty/features/features_bodytype_f.png', "features_bodytype_f.png")
	user << browse_rsc('html/character_ui/dusty/features/features_bodytype_m.png', "features_bodytype_m.png")
	user << browse_rsc('html/character_ui/dusty/features/features_button.png', "features_button.png")
	user << browse_rsc('html/character_ui/dusty/features/features_button_hover.png', "features_button_hover.png")
	user << browse_rsc('html/character_ui/dusty/features/features_random.png', "features_random.png")
	user << browse_rsc('html/character_ui/dusty/features/features_random_hover.png', "features_random_hover.png")
	// Be Special
	user << browse_rsc('html/character_ui/dusty/bespecial/bespecial_no.png', "bespecial_no.png")
	user << browse_rsc('html/character_ui/dusty/bespecial/bespecial_no_hover.png', "bespecial_no_hover.png")
	user << browse_rsc('html/character_ui/dusty/bespecial/bespecial_yes.png', "bespecial_yes.png")
	user << browse_rsc('html/character_ui/dusty/bespecial/bespecial_yes_hover.png', "bespecial_yes_hover.png")
	// Misc Buttons
	user << browse_rsc('html/character_ui/dusty/misc_buttons/ready_order.png', "ready_order.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/ready_order_hover.png', "ready_order_hover.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/change_character.png', "change_character.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/change_character_hover.png', "change_character_hover.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/save.png', "save.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/save_hover.png', "save_hover.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/undo.png', "undo.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/undo_hover.png', "undo_hover.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/done.png', "done.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/done_hover.png', "done_hover.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/keybinds.png', "keybinds.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/keybinds_hover.png', "keybinds_hover.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/toggles.png', "toggles.png")
	user << browse_rsc('html/character_ui/dusty/misc_buttons/toggles_hover.png', "toggles_hover.png")

/datum/preferences/proc/send_grimshart_theme(mob/user)
	// Background
	user << browse_rsc('html/character_ui/grimshart/background&reference/Charsheet_BG.1.png', "Charsheet_BG.1.png")
	// Header
	user << browse_rsc('html/character_ui/grimshart/header/0_header_bg.png', "0_header_bg.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_charname.png', "header_charname.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_class.png', "header_class.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_faith.png', "header_faith.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_playerckey.png', "header_playerckey.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_species.png', "header_species.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_patron.png', "header_patron.png")
	user << browse_rsc('html/character_ui/grimshart/header/header_pq.png', "header_pq.png")
	// Character Preview
	user << browse_rsc('html/character_ui/grimshart/character_preview/charpreview_bg.png', "charpreview_bg.png")
	// Body
	user << browse_rsc('html/character_ui/grimshart/body/0_body_bg.png', "0_body_bg.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_age.png', "body_age.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_flaw.png', "body_flaw.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_dominanthand.png', "body_dominanthand.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_ancestry.png', "body_ancestry.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_pronouns.png', "body_pronouns.png")
	user << browse_rsc('html/character_ui/grimshart/body/body_bodytype.png', "body_bodytype.png")
	// Voice
	user << browse_rsc('html/character_ui/grimshart/voice/0_voice_bg.png', "0_voice_bg.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_type.png', "voice_type.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_accent.png', "voice_accent.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_colour.png', "voice_colour.png")
	user << browse_rsc('html/character_ui/grimshart/voice/voice_colour_blob.png', "voice_colour_blob.png")
	// Family
	user << browse_rsc('html/character_ui/grimshart/family/0_family_bg.png', "0_family_bg.png")
	user << browse_rsc('html/character_ui/grimshart/family/family_type.png', "family_type.png")
	user << browse_rsc('html/character_ui/grimshart/family/gender_pref.png', "gender_pref.png")
	user << browse_rsc('html/character_ui/grimshart/family/spouse_pref.png', "spouse_pref.png")
	// Flavour
	user << browse_rsc('html/character_ui/grimshart/flavour/0_flavour_bg.png', "0_flavour_bg.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_culture.png', "flavour_culture.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_descriptors.png', "flavour_descriptors.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_descriptors_hover.png', "flavour_descriptors_hover.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_text.png', "flavour_text.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_text_hover.png', "flavour_text_hover.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_foodprefs.png', "flavour_foodprefs.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_foodprefs_hover.png', "flavour_foodprefs_hover.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_preview.png', "flavour_preview.png")
	user << browse_rsc('html/character_ui/grimshart/flavour/flavour_preview_hover.png', "flavour_preview_hover.png")
	// Loadout
	user << browse_rsc('html/character_ui/grimshart/loadout/0_loadout_bg.png', "0_loadout_bg.png")
	user << browse_rsc('html/character_ui/grimshart/loadout/loadout_item1.png', "loadout_item1.png")
	user << browse_rsc('html/character_ui/grimshart/loadout/loadout_item2.png', "loadout_item2.png")
	user << browse_rsc('html/character_ui/grimshart/loadout/loadout_item3.png', "loadout_item3.png")
	// Triumphs
	user << browse_rsc('html/character_ui/grimshart/triumphs/0_triumphs_bg.png', "0_triumphs_bg.png")
	user << browse_rsc('html/character_ui/grimshart/triumphs/triumphs_display.png', "triumphs_display.png")
	user << browse_rsc('html/character_ui/grimshart/triumphs/triumphs_shop.png', "triumphs_shop.png")
	user << browse_rsc('html/character_ui/grimshart/triumphs/triumphs_shop_hover.png', "triumphs_shop_hover.png")
	// Headshot
	user << browse_rsc('html/character_ui/grimshart/character_headshot/headshot_bg.png', "headshot_bg.png")
	// OOC
	user << browse_rsc('html/character_ui/grimshart/ooc/0_ooc_bg.png', "0_ooc_bg.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_notes.png', "ooc_notes.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_notes_hover.png', "ooc_notes_hover.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_extra.png', "ooc_extra.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_extra_hover.png', "ooc_extra_hover.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_specialroles.png', "ooc_specialroles.png")
	user << browse_rsc('html/character_ui/grimshart/ooc/ooc_specialroles_hover.png', "ooc_specialroles_hover.png")
	// Features
	user << browse_rsc('html/character_ui/grimshart/features/0_features_bg.png', "0_features_bg.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_bodytype_f.png', "features_bodytype_f.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_bodytype_m.png', "features_bodytype_m.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_button.png', "features_button.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_button_hover.png', "features_button_hover.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_random.png', "features_random.png")
	user << browse_rsc('html/character_ui/grimshart/features/features_random_hover.png', "features_random_hover.png")
	// Be Special
	user << browse_rsc('html/character_ui/grimshart/bespecial/bespecial_no.png', "bespecial_no.png")
	user << browse_rsc('html/character_ui/grimshart/bespecial/bespecial_no_hover.png', "bespecial_no_hover.png")
	user << browse_rsc('html/character_ui/grimshart/bespecial/bespecial_yes.png', "bespecial_yes.png")
	user << browse_rsc('html/character_ui/grimshart/bespecial/bespecial_yes_hover.png', "bespecial_yes_hover.png")
	// Misc Buttons
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/ready_order.png', "ready_order.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/ready_order_hover.png', "ready_order_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/change_character.png', "change_character.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/change_character_hover.png', "change_character_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/save.png', "save.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/save_hover.png', "save_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/undo.png', "undo.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/undo_hover.png', "undo_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/done.png', "done.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/done_hover.png', "done_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/keybinds.png', "keybinds.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/keybinds_hover.png', "keybinds_hover.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/toggles.png', "toggles.png")
	user << browse_rsc('html/character_ui/grimshart/misc_buttons/toggles_hover.png', "toggles_hover.png")

/datum/preferences/proc/send_parchment_theme(mob/user)
	// Background
	user << browse_rsc('html/character_ui/parchment/background&reference/Charsheet_BG.1.png', "Charsheet_BG.1.png")
	// Header
	user << browse_rsc('html/character_ui/parchment/header/0_header_bg.png', "0_header_bg.png")
	user << browse_rsc('html/character_ui/parchment/header/header_charname.png', "header_charname.png")
	user << browse_rsc('html/character_ui/parchment/header/header_class.png', "header_class.png")
	user << browse_rsc('html/character_ui/parchment/header/header_faith.png', "header_faith.png")
	user << browse_rsc('html/character_ui/parchment/header/header_playerckey.png', "header_playerckey.png")
	user << browse_rsc('html/character_ui/parchment/header/header_species.png', "header_species.png")
	user << browse_rsc('html/character_ui/parchment/header/header_patron.png', "header_patron.png")
	user << browse_rsc('html/character_ui/parchment/header/header_pq.png', "header_pq.png")
	// Character Preview
	user << browse_rsc('html/character_ui/parchment/character_preview/charpreview_bg.png', "charpreview_bg.png")
	// Body
	user << browse_rsc('html/character_ui/parchment/body/0_body_bg.png', "0_body_bg.png")
	user << browse_rsc('html/character_ui/parchment/body/body_age.png', "body_age.png")
	user << browse_rsc('html/character_ui/parchment/body/body_flaw.png', "body_flaw.png")
	user << browse_rsc('html/character_ui/parchment/body/body_dominanthand.png', "body_dominanthand.png")
	user << browse_rsc('html/character_ui/parchment/body/body_ancestry.png', "body_ancestry.png")
	user << browse_rsc('html/character_ui/parchment/body/body_pronouns.png', "body_pronouns.png")
	user << browse_rsc('html/character_ui/parchment/body/body_bodytype.png', "body_bodytype.png")
	// Voice
	user << browse_rsc('html/character_ui/parchment/voice/0_voice_bg.png', "0_voice_bg.png")
	user << browse_rsc('html/character_ui/parchment/voice/voice_type.png', "voice_type.png")
	user << browse_rsc('html/character_ui/parchment/voice/voice_accent.png', "voice_accent.png")
	user << browse_rsc('html/character_ui/parchment/voice/voice_colour.png', "voice_colour.png")
	user << browse_rsc('html/character_ui/parchment/voice/voice_colour_blob.png', "voice_colour_blob.png")
	// Family
	user << browse_rsc('html/character_ui/parchment/family/0_family_bg.png', "0_family_bg.png")
	user << browse_rsc('html/character_ui/parchment/family/family_type.png', "family_type.png")
	user << browse_rsc('html/character_ui/parchment/family/gender_pref.png', "gender_pref.png")
	user << browse_rsc('html/character_ui/parchment/family/spouse_pref.png', "spouse_pref.png")
	// Flavour
	user << browse_rsc('html/character_ui/parchment/flavour/0_flavour_bg.png', "0_flavour_bg.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_culture.png', "flavour_culture.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_descriptors.png', "flavour_descriptors.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_descriptors_hover.png', "flavour_descriptors_hover.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_text.png', "flavour_text.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_text_hover.png', "flavour_text_hover.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_foodprefs.png', "flavour_foodprefs.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_foodprefs_hover.png', "flavour_foodprefs_hover.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_preview.png', "flavour_preview.png")
	user << browse_rsc('html/character_ui/parchment/flavour/flavour_preview_hover.png', "flavour_preview_hover.png")
	// Loadout
	user << browse_rsc('html/character_ui/parchment/loadout/0_loadout_bg.png', "0_loadout_bg.png")
	user << browse_rsc('html/character_ui/parchment/loadout/loadout_item1.png', "loadout_item1.png")
	user << browse_rsc('html/character_ui/parchment/loadout/loadout_item2.png', "loadout_item2.png")
	user << browse_rsc('html/character_ui/parchment/loadout/loadout_item3.png', "loadout_item3.png")
	// Triumphs
	user << browse_rsc('html/character_ui/parchment/triumphs/0_triumphs_bg.png', "0_triumphs_bg.png")
	user << browse_rsc('html/character_ui/parchment/triumphs/triumphs_display.png', "triumphs_display.png")
	user << browse_rsc('html/character_ui/parchment/triumphs/triumphs_shop.png', "triumphs_shop.png")
	user << browse_rsc('html/character_ui/parchment/triumphs/triumphs_shop_hover.png', "triumphs_shop_hover.png")
	// Headshot
	user << browse_rsc('html/character_ui/parchment/character_headshot/headshot_bg.png', "headshot_bg.png")
	// OOC
	user << browse_rsc('html/character_ui/parchment/ooc/0_ooc_bg.png', "0_ooc_bg.png")
	user << browse_rsc('html/character_ui/parchment/ooc/ooc_notes.png', "ooc_notes.png")
	user << browse_rsc('html/character_ui/parchment/ooc/ooc_notes_hover.png', "ooc_notes_hover.png")
	user << browse_rsc('html/character_ui/parchment/ooc/ooc_extra.png', "ooc_extra.png")
	user << browse_rsc('html/character_ui/parchment/ooc/ooc_extra_hover.png', "ooc_extra_hover.png")
	user << browse_rsc('html/character_ui/parchment/ooc/ooc_specialroles.png', "ooc_specialroles.png")
	user << browse_rsc('html/character_ui/parchment/ooc/ooc_specialroles_hover.png', "ooc_specialroles_hover.png")
	// Features
	user << browse_rsc('html/character_ui/parchment/features/0_features_bg.png', "0_features_bg.png")
	user << browse_rsc('html/character_ui/parchment/features/features_bodytype_f.png', "features_bodytype_f.png")
	user << browse_rsc('html/character_ui/parchment/features/features_bodytype_m.png', "features_bodytype_m.png")
	user << browse_rsc('html/character_ui/parchment/features/features_button.png', "features_button.png")
	user << browse_rsc('html/character_ui/parchment/features/features_button_hover.png', "features_button_hover.png")
	user << browse_rsc('html/character_ui/parchment/features/features_random.png', "features_random.png")
	user << browse_rsc('html/character_ui/parchment/features/features_random_hover.png', "features_random_hover.png")
	// Be Special
	user << browse_rsc('html/character_ui/parchment/bespecial/bespecial_no.png', "bespecial_no.png")
	user << browse_rsc('html/character_ui/parchment/bespecial/bespecial_no_hover.png', "bespecial_no_hover.png")
	user << browse_rsc('html/character_ui/parchment/bespecial/bespecial_yes.png', "bespecial_yes.png")
	user << browse_rsc('html/character_ui/parchment/bespecial/bespecial_yes_hover.png', "bespecial_yes_hover.png")
	// Misc Buttons
	user << browse_rsc('html/character_ui/parchment/misc_buttons/ready_order.png', "ready_order.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/ready_order_hover.png', "ready_order_hover.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/change_character.png', "change_character.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/change_character_hover.png', "change_character_hover.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/save.png', "save.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/save_hover.png', "save_hover.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/undo.png', "undo.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/undo_hover.png', "undo_hover.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/done.png', "done.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/done_hover.png', "done_hover.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/keybinds.png', "keybinds.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/keybinds_hover.png', "keybinds_hover.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/toggles.png', "toggles.png")
	user << browse_rsc('html/character_ui/parchment/misc_buttons/toggles_hover.png', "toggles_hover.png")

/datum/preferences/proc/send_paper_theme(mob/user)
	// Background
	user << browse_rsc('html/character_ui/paper/background&reference/Charsheet_BG.1.png', "Charsheet_BG.1.png")
	// Header
	user << browse_rsc('html/character_ui/paper/header/0_header_bg.png', "0_header_bg.png")
	user << browse_rsc('html/character_ui/paper/header/header_charname.png', "header_charname.png")
	user << browse_rsc('html/character_ui/paper/header/header_class.png', "header_class.png")
	user << browse_rsc('html/character_ui/paper/header/header_faith.png', "header_faith.png")
	user << browse_rsc('html/character_ui/paper/header/header_playerckey.png', "header_playerckey.png")
	user << browse_rsc('html/character_ui/paper/header/header_species.png', "header_species.png")
	user << browse_rsc('html/character_ui/paper/header/header_patron.png', "header_patron.png")
	user << browse_rsc('html/character_ui/paper/header/header_pq.png', "header_pq.png")
	// Character Preview
	user << browse_rsc('html/character_ui/paper/character_preview/charpreview_bg.png', "charpreview_bg.png")
	// Body
	user << browse_rsc('html/character_ui/paper/body/0_body_bg.png', "0_body_bg.png")
	user << browse_rsc('html/character_ui/paper/body/body_age.png', "body_age.png")
	user << browse_rsc('html/character_ui/paper/body/body_flaw.png', "body_flaw.png")
	user << browse_rsc('html/character_ui/paper/body/body_dominanthand.png', "body_dominanthand.png")
	user << browse_rsc('html/character_ui/paper/body/body_ancestry.png', "body_ancestry.png")
	user << browse_rsc('html/character_ui/paper/body/body_pronouns.png', "body_pronouns.png")
	user << browse_rsc('html/character_ui/paper/body/body_bodytype.png', "body_bodytype.png")
	// Voice
	user << browse_rsc('html/character_ui/paper/voice/0_voice_bg.png', "0_voice_bg.png")
	user << browse_rsc('html/character_ui/paper/voice/voice_type.png', "voice_type.png")
	user << browse_rsc('html/character_ui/paper/voice/voice_accent.png', "voice_accent.png")
	user << browse_rsc('html/character_ui/paper/voice/voice_colour.png', "voice_colour.png")
	user << browse_rsc('html/character_ui/paper/voice/voice_colour_blob.png', "voice_colour_blob.png")
	// Family
	user << browse_rsc('html/character_ui/paper/family/0_family_bg.png', "0_family_bg.png")
	user << browse_rsc('html/character_ui/paper/family/family_type.png', "family_type.png")
	user << browse_rsc('html/character_ui/paper/family/gender_pref.png', "gender_pref.png")
	user << browse_rsc('html/character_ui/paper/family/spouse_pref.png', "spouse_pref.png")
	// Flavour
	user << browse_rsc('html/character_ui/paper/flavour/0_flavour_bg.png', "0_flavour_bg.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_culture.png', "flavour_culture.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_descriptors.png', "flavour_descriptors.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_descriptors_hover.png', "flavour_descriptors_hover.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_text.png', "flavour_text.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_text_hover.png', "flavour_text_hover.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_foodprefs.png', "flavour_foodprefs.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_foodprefs_hover.png', "flavour_foodprefs_hover.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_preview.png', "flavour_preview.png")
	user << browse_rsc('html/character_ui/paper/flavour/flavour_preview_hover.png', "flavour_preview_hover.png")
	// Loadout
	user << browse_rsc('html/character_ui/paper/loadout/0_loadout_bg.png', "0_loadout_bg.png")
	user << browse_rsc('html/character_ui/paper/loadout/loadout_item1.png', "loadout_item1.png")
	user << browse_rsc('html/character_ui/paper/loadout/loadout_item2.png', "loadout_item2.png")
	user << browse_rsc('html/character_ui/paper/loadout/loadout_item3.png', "loadout_item3.png")
	// Triumphs
	user << browse_rsc('html/character_ui/paper/triumphs/0_triumphs_bg.png', "0_triumphs_bg.png")
	user << browse_rsc('html/character_ui/paper/triumphs/triumphs_display.png', "triumphs_display.png")
	user << browse_rsc('html/character_ui/paper/triumphs/triumphs_shop.png', "triumphs_shop.png")
	user << browse_rsc('html/character_ui/paper/triumphs/triumphs_shop_hover.png', "triumphs_shop_hover.png")
	// Headshot
	user << browse_rsc('html/character_ui/paper/character_headshot/headshot_bg.png', "headshot_bg.png")
	// OOC
	user << browse_rsc('html/character_ui/paper/ooc/0_ooc_bg.png', "0_ooc_bg.png")
	user << browse_rsc('html/character_ui/paper/ooc/ooc_notes.png', "ooc_notes.png")
	user << browse_rsc('html/character_ui/paper/ooc/ooc_notes_hover.png', "ooc_notes_hover.png")
	user << browse_rsc('html/character_ui/paper/ooc/ooc_extra.png', "ooc_extra.png")
	user << browse_rsc('html/character_ui/paper/ooc/ooc_extra_hover.png', "ooc_extra_hover.png")
	user << browse_rsc('html/character_ui/paper/ooc/ooc_specialroles.png', "ooc_specialroles.png")
	user << browse_rsc('html/character_ui/paper/ooc/ooc_specialroles_hover.png', "ooc_specialroles_hover.png")
	// Features
	user << browse_rsc('html/character_ui/paper/features/0_features_bg.png', "0_features_bg.png")
	user << browse_rsc('html/character_ui/paper/features/features_bodytype_f.png', "features_bodytype_f.png")
	user << browse_rsc('html/character_ui/paper/features/features_bodytype_m.png', "features_bodytype_m.png")
	user << browse_rsc('html/character_ui/paper/features/features_button.png', "features_button.png")
	user << browse_rsc('html/character_ui/paper/features/features_button_hover.png', "features_button_hover.png")
	user << browse_rsc('html/character_ui/paper/features/features_random.png', "features_random.png")
	user << browse_rsc('html/character_ui/paper/features/features_random_hover.png', "features_random_hover.png")
	// Be Special
	user << browse_rsc('html/character_ui/paper/bespecial/bespecial_no.png', "bespecial_no.png")
	user << browse_rsc('html/character_ui/paper/bespecial/bespecial_no_hover.png', "bespecial_no_hover.png")
	user << browse_rsc('html/character_ui/paper/bespecial/bespecial_yes.png', "bespecial_yes.png")
	user << browse_rsc('html/character_ui/paper/bespecial/bespecial_yes_hover.png', "bespecial_yes_hover.png")
	// Misc Buttons
	user << browse_rsc('html/character_ui/paper/misc_buttons/ready_order.png', "ready_order.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/ready_order_hover.png', "ready_order_hover.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/change_character.png', "change_character.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/change_character_hover.png', "change_character_hover.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/save.png', "save.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/save_hover.png', "save_hover.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/undo.png', "undo.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/undo_hover.png', "undo_hover.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/done.png', "done.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/done_hover.png', "done_hover.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/keybinds.png', "keybinds.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/keybinds_hover.png', "keybinds_hover.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/toggles.png', "toggles.png")
	user << browse_rsc('html/character_ui/paper/misc_buttons/toggles_hover.png', "toggles_hover.png")
