#include "code\modules\client\topic_census.dm"
#include "code\modules\smallclothes\accessories.dm"
#include "code\modules\smallclothes\customizers.dm"
#include "code\modules\client\preferences\character_menu.dm"
#include "code\modules\client\preferences\features_tgui.dm"
#include "code\modules\client\preferences\character_setup_hooks.dm"
#include "code\modules\smallclothes\preferences.dm"
#include "code\modules\smallclothes\rendering.dm"
